/**
 * DRY-RUN generator for the Step 3c colour-cosmetics decontam backfill.
 * WRITES NOTHING to the database. It only emits a reviewable SQL file
 * (.skincare-colour-backfill.gen.sql) and prints a summary + samples.
 *
 * Method (match_key discipline): read every stored top_category='skincare' row
 * (products_active, excl. cleanup_remove), run the SHIPPED inferCategorisation
 * AND the pre-change (git HEAD) version, and take the DELTA — rows the Step 3c
 * change now routes OUT of skincare. Those exact ids, grouped by destination
 * (top/sub/type/tags), become guarded UPDATEs. A snapshot table of the current
 * values is created first so the change is reversible.
 *
 * Run:  npx tsx scripts/skincare-colour-backfill.mts
 * Then review scripts/.skincare-colour-backfill.gen.sql before any apply.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { inferCategorisation as inferNew } from "../supabase/functions/_shared/categorisation.ts";
import { inferCategorisation as inferOld } from "./.categorisation-old.gen.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SNAP = "fmb_skincare_colour_snapshot_20260701";
const env = Object.fromEntries(
  readFileSync(join(__dirname, "..", ".env.local"), "utf8").split(/\n/).filter((l) => l.includes("="))
    .map((l) => { const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; }),
);
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false } });

type Row = { id: number; name: string | null; brand: string | null; subcategory: string | null; product_type: string | null };
async function fetchAll(): Promise<Row[]> {
  const byId = new Map<number, Row>();
  for (let offset = 0; ; offset += 1000) {
    const { data, error } = await sb.from("products_active")
      .select("id, name, brand, subcategory, product_type")
      .eq("top_category", "skincare").not("tags", "cs", "{cleanup_remove}")
      .order("id", { ascending: true }).range(offset, offset + 999);
    if (error) throw new Error(error.message);
    if (!data || data.length === 0) break;
    for (const r of data as Row[]) byId.set(r.id, r);
    if (data.length < 1000) break;
  }
  return [...byId.values()];
}

const rows = await fetchAll();
type Move = { r: Row; top: string; sub: string; pt: string; tags: string[] };
const delta: Move[] = [];
for (const r of rows) {
  const name = r.name || "", brand = r.brand || "";
  const nu = inferNew(name, brand), ol = inferOld(name, brand);
  if (nu.excluded || nu.top_category === "skincare") continue;
  if (!ol.excluded && ol.top_category === "skincare") delta.push({ r, top: nu.top_category!, sub: nu.subcategory, pt: nu.product_type, tags: nu.tags });
}

// group by identical target (top/sub/type/tags)
const groups = new Map<string, Move[]>();
for (const m of delta) {
  const key = `${m.top}|${m.sub}|${m.pt}|${JSON.stringify(m.tags)}`;
  (groups.get(key) ?? groups.set(key, []).get(key)!).push(m);
}
const ordered = [...groups.entries()].sort((a, b) => b[1].length - a[1].length);

// ── emit SQL ────────────────────────────────────────────────────────────────
const allIds = delta.map((m) => m.r.id).sort((a, b) => a - b);
const sqlLit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (ids: number[]) => `array[${ids.join(",")}]::int[]`;
let sql = `-- Step 3c colour-cosmetics decontam backfill (DRY-RUN ARTIFACT — review before apply).
-- Generated by scripts/skincare-colour-backfill.mts from the SHIPPED inferCategorisation.
-- ${delta.length} rows move OUT of skincare (colour cosmetics mis-shelved by feeds).
--
-- Safety:
--   * snapshot table ${SNAP} captures current values first (reversible);
--   * every UPDATE guarded by top_category='skincare' (drifted rows are skipped, not clobbered);
--   * ids are explicit (no name predicate) — exactly the detector-matched set;
--   * tags follow the categoriser contract (tags = [top, sub]).
-- Idempotent: re-running is a no-op (rows are no longer 'skincare' after apply).

begin;

-- 1. Snapshot (reversible): current category state of every affected row.
create table if not exists ${SNAP} as
select id, top_category, subcategory, product_type, tags, now() as snapshot_at
from products
where id = any(${arr(allIds)});

`;
let n = 0;
for (const [key, arrRows] of ordered) {
  const [top, sub, pt] = key.split("|");
  const tags = arrRows[0].tags;
  const ids = arrRows.map((m) => m.r.id).sort((a, b) => a - b);
  n++;
  sql += `-- ${n}. ${top}/${sub}/${pt}  (${ids.length} rows)\n`;
  sql += `update products set\n  top_category = ${sqlLit(top)}, subcategory = ${sqlLit(sub)}, product_type = ${sqlLit(pt)}, tags = array[${tags.map(sqlLit).join(",")}]\nwhere top_category = 'skincare' and id = any(${arr(ids)});\n\n`;
}
sql += `commit;\n\n`;
sql += `-- Rollback (if needed, after apply): restore every row from the snapshot.
-- begin;
-- update products p set
--   top_category = s.top_category, subcategory = s.subcategory,
--   product_type = s.product_type, tags = s.tags
-- from ${SNAP} s where p.id = s.id;
-- commit;
`;
const out = join(__dirname, ".skincare-colour-backfill.gen.sql");
writeFileSync(out, sql);

// ── summary ─────────────────────────────────────────────────────────────────
console.log(`stored skincare scanned: ${rows.length}`);
console.log(`DELTA rows to backfill:  ${delta.length}\n`);
console.log(`snapshot table: ${SNAP} (${allIds.length} rows)\n`);
console.log(`grouped UPDATEs:`);
for (const [key, arrRows] of ordered) {
  const [top, sub, pt] = key.split("|");
  console.log(`  ${String(arrRows.length).padStart(4)}  ${top}/${sub}/${pt}   tags=${JSON.stringify(arrRows[0].tags)}`);
}
console.log(`\nsample before -> after (3 per group):`);
for (const [key, arrRows] of ordered) {
  const [top, sub, pt] = key.split("|");
  console.log(`\n  ${top}/${sub}/${pt}:`);
  for (const m of arrRows.slice(0, 3))
    console.log(`    [${m.r.id}] skincare/${m.r.subcategory}/${m.r.product_type}  ->  ${top}/${sub}/${pt}   | ${m.r.brand} — ${m.r.name}`);
}
console.log(`\nSQL written (NOT applied): ${out}`);
